<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'خانه',
    'Login' => 'ورود',
    'Reset' => '',
    'Update User: {nameAttribute}' => '',
    'Update Youtube Video: {nameAttribute}' => '',
    'Videos' => 'ویدیوها',
    'Youtube Videos' => 'ویدیوهای یوتیوب',
    'Are you sure you want to delete this item?' => 'آیا از حذف این مورد مطمین هستید؟',
    'Channel ID' => 'شناسه کانال',
    'Channel Title' => 'عنوان کانال',
    'Create User' => 'ساخت کاربر',
    'Delete' => 'حذف',
    'Description' => 'توضیحات',
    'ID' => 'شناسه',
    'Owner' => 'مالک',
    'Owner ID' => 'شناسه مالک',
    'Published At' => 'منتشرشده در',
    'Save' => 'دخیره',
    'Search' => 'جستجو',
    'Sync with Youtube' => 'همگام سازی با یوتیوب',
    'The requested page does not exist.' => 'صفحه درخواست شده وجود ندارد.',
    'Title' => 'عنوان',
    'Update' => 'ویرایش',
    'Users' => 'کاربران',
    'Video ID' => 'شناسه ویدیو',
    'Video count' => 'تعداد ویدیو',
];
